# AirGradient ONE - Board v9
# https://www.airgradient.com/open-airgradient/instructions/overview/

# Needs ESPHome 2023.7.0 or later

# Loosely inspired from https://github.com/MallocArray/airgradient_esphome.git


# Note: flashing via usb may fail, with esphome asking you to run an esptool.py 
# command manually. Try adding '--no-stub' to this command in that case


substitutions:
  devicename: "airgradient-one"
  upper_devicename: "AG One"
  ag_esphome_config_version: 0.1.0

esphome:
  name: "${devicename}"
  friendly_name: "${upper_devicename}"
  name_add_mac_suffix: true  # Set to false if you don't want part of the MAC address in the name

esp32:
  board: esp32-c3-devkitm-1

# Disable logging
# https://esphome.io/components/logger.html
logger:
  baud_rate: 0  # Must disable serial logging as ESP32-C3 only has 2 hardware UART and both are in use
  logs:
    component: ERROR  # Hiding warning messages about component taking a long time https://github.com/esphome/issues/issues/4717

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password  

# The captive portal is a fallback mechanism for when connecting to the configured WiFi fails.
# https://esphome.io/components/captive_portal.html
captive_portal:


# Two numbers that can be piloted by home assitant and are displayed on the oled sceen
number:
  - platform: template
    name: "Exterior Temperature"
    id: "exterior_temp"
    optimistic: true
    min_value: -50
    max_value: 100
    step: 0.1
    unit_of_measurement: "°C"
  - platform: template
    name: "Exterior Humidity"
    id: "exterior_humidity"
    optimistic: true
    min_value: 0
    max_value: 100
    step: 1
    unit_of_measurement: "%"

# Create a switch for safe_mode in order to flash the device
# Solution from this thread:
# https://community.home-assistant.io/t/esphome-flashing-over-wifi-does-not-work/357352/1
switch:
  - platform: safe_mode
    name: "Flash Mode (Safe Mode)"
    icon: "mdi:cellphone-arrow-down"
  - platform: template
    name: "Display Temperature in °F"
    icon: "mdi:thermometer"
    id: display_in_f
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: True
  - platform: template
    name: "Enable strip"
    id: enable_strip
    icon: "mdi:led-strip"
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: True
  - platform: template
    name: "Enable display"
    id: enable_display
    icon: "mdi:monitor"
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: True
    turn_on_action:
      - lambda: id(oled_display).turn_on();
    turn_off_action:
      - lambda: id(oled_display).turn_off();
    


uart:
  # https://esphome.io/components/uart.html#uart
  - rx_pin: GPIO0  # Pin 12
    tx_pin: GPIO1  # Pin 13
    baud_rate: 9600
    id: senseair_s8_uart

  - rx_pin: GPIO20  # Pin 30 or RX
    tx_pin: GPIO21  # Pin 31, or TX
    baud_rate: 9600
    id: pms5003_uart

i2c:
  # https://esphome.io/components/i2c.html
  sda: GPIO7
  scl: GPIO6
  frequency: 400kHz  # 400kHz eliminates warnings about components taking a long time other than SGP40 component: https://github.com/esphome/issues/issues/4717

sensor:
  - platform: pmsx003
    # PMS5003 https://esphome.io/components/sensor/pmsx003.html
    type: PMSX003
    uart_id: pms5003_uart
    pm_2_5:
      name: "PM 2.5"
      id: pm_2_5
      on_value:
        lambda: |-
          // https://en.wikipedia.org/wiki/Air_quality_index#Computing_the_AQI
          // Borrowed from https://github.com/kylemanna/sniffer/blob/master/esphome/sniffer_common.yaml
          if (id(pm_2_5).state <= 12.0) {
            // good
            id(pm_2_5_aqi).publish_state((50.0 - 0.0) / (12.0 - 0.0) * (id(pm_2_5).state - 0.0) + 0.0);
          } else if (id(pm_2_5).state <= 35.4) {
            // moderate
            id(pm_2_5_aqi).publish_state((100.0 - 51.0) / (35.4 - 12.1) * (id(pm_2_5).state - 12.1) + 51.0);
          } else if (id(pm_2_5).state <= 55.4) {
            // usg
            id(pm_2_5_aqi).publish_state((150.0 - 101.0) / (55.4 - 35.5) * (id(pm_2_5).state - 35.5) + 101.0);
          } else if (id(pm_2_5).state <= 150.4) {
            // unhealthy
            id(pm_2_5_aqi).publish_state((200.0 - 151.0) / (150.4 - 55.5) * (id(pm_2_5).state - 55.5) + 151.0);
          } else if (id(pm_2_5).state <= 250.4) {
            // very unhealthy
            id(pm_2_5_aqi).publish_state((300.0 - 201.0) / (250.4 - 150.5) * (id(pm_2_5).state - 150.5) + 201.0);
          } else if (id(pm_2_5).state <= 350.4) {
            // hazardous
            id(pm_2_5_aqi).publish_state((400.0 - 301.0) / (350.4 - 250.5) * (id(pm_2_5).state - 250.5) + 301.0);
          } else if (id(pm_2_5).state <= 500.4) {
            // hazardous 2
            id(pm_2_5_aqi).publish_state((500.0 - 401.0) / (500.4 - 350.5) * (id(pm_2_5).state - 350.5) + 401.0);
          } else {
            id(pm_2_5_aqi).publish_state(500);
          }
    pm_1_0:
      name: "PM 1.0"
      id: pm_1_0
    pm_10_0:
      name: "PM 10.0"
      id: pm_10_0
    pm_0_3um:
      name: "PM 0.3"
      id: pm_0_3um
    update_interval: 2min

  - platform: template
    name: "PM 2.5 AQI"
    unit_of_measurement: "AQI"
    icon: "mdi:air-filter"
    accuracy_decimals: 0
    id: pm_2_5_aqi

  - platform: senseair
    # SenseAir S8 https://esphome.io/components/sensor/senseair.html
    # https://senseair.com/products/size-counts/s8-lp/
    co2:
      name: "SenseAir S8 CO2"
      id: co2
      filters:
        - skip_initial: 2
        - clamp:
            min_value: 400  # 419 as of 2023-06 https://gml.noaa.gov/ccgg/trends/global.html
      on_value:
        - if:
            condition:
                lambda: 'return id(enable_strip).state && id(co2).state < 800;'
            then:
              - light.turn_on:
                  id: led_strip
                  brightness: 100%
                  red: 0%
                  green: 100%
                  blue: 0%
        - if:
            condition:
                lambda: 'return id(enable_strip).state && id(co2).state >= 800 && id(co2).state < 1000;'
            then:
              - light.turn_on:
                  id: led_strip
                  brightness: 100%
                  red: 100%
                  green: 100%
                  blue: 0%
        - if:
            condition:
                lambda: 'return id(enable_strip).state && id(co2).state >= 1000 && id(co2).state < 1500;'
            then:
              - light.turn_on:
                  id: led_strip
                  brightness: 100%
                  red: 100%
                  green: 50%
                  blue: 0%
        - if:
            condition:
                lambda: 'return !id(enable_strip).state && id(co2).state < 1500;'
            then:
              - light.turn_off:
                  id: led_strip
        - if:
            condition:
                lambda: 'return id(co2).state >= 1500 && id(co2).state < 2000;'
            then:
              - light.turn_on:
                  id: led_strip
                  brightness: 100%
                  red: 100%
                  green: 0%
                  blue: 0%
        - if:
            condition:
                lambda: 'return id(co2).state >= 2000 && id(co2).state < 3000;'
            then:
              - light.turn_on:
                  id: led_strip
                  brightness: 100%
                  red: 60%
                  green: 0%
                  blue: 60%
        - if:
            condition:
                lambda: 'return id(co2).state >= 3000 && id(co2).state < 10000;'
            then:
              - light.turn_on:
                  id: led_strip
                  brightness: 100%
                  red: 40%
                  green: 0%
                  blue: 0%
    id: senseair_s8
    uart_id: senseair_s8_uart


  - platform: sht4x
    # SHT40 https://esphome.io/components/sensor/sht4x.html
    temperature:
      name: "Temperature"
      id: temp
    humidity:
      name: "Humidity"
      id: humidity
    address: 0x44

  # - platform: sht3xd
  #   # SHT30 https://esphome.io/components/sensor/sht3xd.html
  #   temperature:
  #     name: "Temperature"
  #     id: temp
  #   humidity:
  #     name: "Humidity"
  #     id: humidity
  #   address: 0x44
  #   heater_enabled: false  # Only enable if in conditions that may have high condensation

  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_dbm
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    id: device_uptime
    update_interval: 10s

  - platform: sgp4x
    # SGP41 https://esphome.io/components/sensor/sgp4x.html
    voc:
      name: "VOC Index"
      id: voc
    nox:
      name: "NOx Index"
      id: nox
    compensation:  # Remove this block if no temp/humidity sensor present for compensation
      temperature_source: temp
      humidity_source: humidity


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
    name: "Display in °F"
    id: display_toggle_button
    on_release:
      then:
        - switch.toggle: display_in_f


font:
    # Font to use on the display
    # Open Source font Liberation Sans by Red Hat
    # https://www.dafont.com/liberation-sans.font
  # - file: "./fonts/liberation_sans/LiberationSans-Regular.ttf"
  - file:
      type: gfonts
      family: Poppins
      weight: light
    id: poppins_light
    size: 14
    glyphs: '!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/µ³'
  - file:
      type: gfonts
      family: Poppins
      weight: light
    id: poppins_light_12
    size: 12
    glyphs: '!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/µ³'
  - file: "gfonts://Ubuntu Mono"
    id: ubuntu
    size: 22
    glyphs: '!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/µ³'

display:
  # https://esphome.io/components/display/ssd1306.html
  # Formatting reference: https://www.tutorialspoint.com/c_standard_library/c_function_printf.htm
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    id: oled_display
    address: 0x3C
    # rotation: 180°
    pages:
      # - id: summary1
      #   lambda: |-
      #     it.printf(0, 0, id(poppins_light), "CO2:");
      #     it.printf(128, 0, id(poppins_light), TextAlign::TOP_RIGHT, "%.0f ppm", id(co2).state);
      #     it.printf(0, 16, id(poppins_light), "PM2.5:");
      #     it.printf(128, 16, id(poppins_light), TextAlign::TOP_RIGHT, "%.0f µg/m³", id(pm_2_5).state);
      #     it.printf(0, 32, id(poppins_light), "Temp:");
      #     if (id(display_in_f).state) {
      #       it.printf(128, 32, id(poppins_light), TextAlign::TOP_RIGHT, "%.1f°F", id(temp).state*9/5+32);
      #     } else {
      #       it.printf(128, 32, id(poppins_light), TextAlign::TOP_RIGHT, "%.1f°C", id(temp).state);
      #     }
      #     it.printf(0, 48, id(poppins_light), "Humidity:");
      #     it.printf(128, 48, id(poppins_light), TextAlign::TOP_RIGHT, "%.1f%%", id(humidity).state);
      # - id: summary2
      #   lambda: |-
      #     it.printf(0, 0, id(poppins_light), "CO2:");
      #     it.printf(128, 0, id(poppins_light), TextAlign::TOP_RIGHT, "%.0f ppm", id(co2).state);
      #     it.printf(0, 16, id(poppins_light), "PM2.5:");
      #     it.printf(128, 16, id(poppins_light), TextAlign::TOP_RIGHT, "%.0f µg/m³", id(pm_2_5).state);
      #     it.printf(0, 32, id(poppins_light), "VOC:");
      #     it.printf(128, 32, id(poppins_light), TextAlign::TOP_RIGHT, "%.0f", id(voc).state);
      #     it.printf(0, 48, id(poppins_light), "NOx:");
      #     it.printf(128, 48, id(poppins_light), TextAlign::TOP_RIGHT, "%.0f", id(nox).state);   
      - id: summary3
        lambda: |-
          it.printf(0, 0, id(poppins_light), "PM0.3:");
          it.printf(128, 0, id(poppins_light), TextAlign::TOP_RIGHT, "%.0f /dL", id(pm_0_3um).state);
          it.printf(0, 16, id(poppins_light), "PM1.0:");
          it.printf(128, 16, id(poppins_light), TextAlign::TOP_RIGHT, "%.0f µg/m³", id(pm_1_0).state);
          it.printf(0, 32, id(poppins_light), "PM2.5:");
          it.printf(128, 32, id(poppins_light), TextAlign::TOP_RIGHT, "%.0f µg/m³", id(pm_2_5).state);
          it.printf(0, 48, id(poppins_light), "PM10:");
          it.printf(128, 48, id(poppins_light), TextAlign::TOP_RIGHT, "%.0f µg/m³", id(pm_10_0).state);
      - id: summary4
        lambda: |-
          it.printf(0, 0, id(poppins_light), "CO2:");
          it.printf(128, 0, id(poppins_light), TextAlign::TOP_RIGHT, "%.0f ppm", id(co2).state);
          it.printf(0, 16, id(poppins_light), "PM2.5:");
          it.printf(128, 16, id(poppins_light), TextAlign::TOP_RIGHT, "%.0f AQI", id(pm_2_5_aqi).state);
          it.printf(0, 32, id(poppins_light), "VOC:");
          it.printf(128, 32, id(poppins_light), TextAlign::TOP_RIGHT, "%.0f", id(voc).state);
          it.printf(0, 48, id(poppins_light), "NOx:");
          it.printf(128, 48, id(poppins_light), TextAlign::TOP_RIGHT, "%.0f", id(nox).state);  
      - id: summary5
        lambda: |-
          it.printf(0, 0, id(poppins_light), "In temp:");
          if (id(display_in_f).state) {
            it.printf(128, 0, id(poppins_light), TextAlign::TOP_RIGHT, "%.1f°F", id(temp).state*9/5+32);
          } else {
            it.printf(128, 0, id(poppins_light), TextAlign::TOP_RIGHT, "%.1f°C", id(temp).state);
          }
          it.printf(0, 16, id(poppins_light), "In hum:");
          it.printf(128, 16, id(poppins_light), TextAlign::TOP_RIGHT, "%.0f%%", id(humidity).state);
          it.printf(0, 32, id(poppins_light), "Out temp:");
          if (id(display_in_f).state) {
            it.printf(128, 32, id(poppins_light), TextAlign::TOP_RIGHT, "%.1f°F", id(exterior_temp).state*9/5+32);
          } else {
            it.printf(128, 32, id(poppins_light), TextAlign::TOP_RIGHT, "%.1f°C", id(exterior_temp).state);
          }
          it.printf(0, 48, id(poppins_light), "Out hum:");
          it.printf(128, 48, id(poppins_light), TextAlign::TOP_RIGHT, "%.0f%%", id(exterior_humidity).state);  
      # - id: air_quality
      #   lambda: |-
      #     it.printf(0, 6, id(ubuntu), "CO2");
      #     it.printf(128, 6, id(ubuntu), TextAlign::TOP_RIGHT, "%.0f ppm", id(co2).state);
      #     it.printf(0, 34, id(ubuntu), "PM2");
      #     it.printf(128, 34, id(ubuntu), TextAlign::TOP_RIGHT, "%.0f µg/m³", id(pm_2_5).state);
      # - id: air_temp
      #   lambda: |-
      #     it.printf(0, 6, id(ubuntu), "Temp");
      #     if (id(display_in_f).state) {
      #       it.printf(128, 6, id(ubuntu), TextAlign::TOP_RIGHT, "%.1f°F", id(temp).state*9/5+32);
      #     } else {
      #       it.printf(128, 6, id(ubuntu), TextAlign::TOP_RIGHT, "%.1f°C", id(temp).state);
      #     }
      #     it.printf(0, 34, id(ubuntu), "Humid");
      #     it.printf(128, 34, id(ubuntu), TextAlign::TOP_RIGHT, "%.1f%%", id(humidity).state);
      # - id: tvoc
      #   lambda: |-
      #     it.printf(0, 6, id(ubuntu), "VOC:");
      #     it.printf(128, 6, id(ubuntu), TextAlign::TOP_RIGHT, "%.0f", id(voc).state);
      #     it.printf(0, 34, id(ubuntu), "NOx:");
      #     it.printf(128, 34, id(ubuntu), TextAlign::TOP_RIGHT, "%.0f", id(nox).state);
      # - id: combo
      #   lambda: |-
      #     if (id(display_in_f).state) {
      #       it.printf(0, 0, id(poppins_light_12), "%.1f °F", id(temp).state*9/5+32);
      #     } else {
      #       it.printf(0, 0, id(poppins_light_12), "%.1f °C", id(temp).state);
      #     }
      #     it.printf(128, 0, id(poppins_light_12), TextAlign::TOP_RIGHT, "%.1f%%", id(humidity).state);
      #     it.printf(0, 16, id(poppins_light_12), "%.0f µg", id(pm_2_5).state);
      #     it.printf(128, 16, id(poppins_light_12), TextAlign::TOP_RIGHT, "%.0f ppm", id(co2).state);
      #     it.printf(0, 32, id(poppins_light_12), "VOC: %.0f", id(voc).state);
      #     it.printf(128, 32, id(poppins_light_12), TextAlign::TOP_RIGHT, "NOx: %.0f", id(nox).state);
      #     it.printf(0, 48, id(poppins_light_12), "AQI: %.0f", id(pm_2_5_aqi).state);
      - id: boot
        lambda: |-
          it.printf(0, 0, id(poppins_light), "ID:");
          it.printf(128, 0, id(poppins_light), TextAlign::TOP_RIGHT, "%s", get_mac_address().c_str());
          it.printf(0, 21, id(poppins_light), "Config Ver: $ag_esphome_config_version");
          it.printf(0, 42, id(poppins_light), "$upper_devicename");

    on_page_change:
      to: boot
      then:
        - if:
            # Skip the boot page after initial boot
            condition:
                lambda: 'return id(device_uptime).state > 30;'
            then:
              - display.page.show_next: oled_display
              - component.update: oled_display

button:
  # https://github.com/esphome/issues/issues/2444
  - platform: template
    name: SenseAir S8 Calibration
    id: senseair_s8_calibrate_button
    on_press:
      then:
        - senseair.background_calibration: senseair_s8
        - delay: 70s
        - senseair.background_calibration_result: senseair_s8
  - platform: template
    name: SenseAir S8 Enable Automatic Calibration
    id: senseair_s8_enable_calibrate_button
    on_press:
      then:
        - senseair.abc_enable: senseair_s8
  - platform: template
    name: SenseAir S8 Disable Automatic Calibration
    id: senseair_s8_disable_calibrate_button
    on_press:
      then:
        - senseair.abc_disable: senseair_s8

output:
  - platform: gpio
    # Watchdog to reboot if no activity
    id: watchdog
    pin: GPIO2

light:
    # https://esphome.io/components/light/esp32_rmt_led_strip.html
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO10  # Pin 16
    num_leds: 11
    rmt_channel: 0
    chipset: ws2812
    name: "LED Strip"
    id: led_strip

http_request:
  # Used to support POST request to send data to AirGradient
  # https://esphome.io/components/http_request.html


interval:
  - interval: 30s
    # Notify watchdog device is still alive
    then:
      - output.turn_on: watchdog
      - delay: 20ms
      - output.turn_off: watchdog

  - interval: 10s
    # Automatically switch to the next page every five seconds
    then:
      - if:
          # Show boot screen for first 10 seconds with serial number and config version
          condition:
              lambda: 'return id(device_uptime).state < 10;'
          then:
            - display.page.show: boot
            - lambda: id(device_uptime).set_update_interval(1);
          else:
            # Change page on display
            - display.page.show_next: oled_display
            - component.update: oled_display


