substitutions:
  device_name: arrosoir

esphome:
  name: "${device_name}"
  name_add_mac_suffix: true 
  platformio_options:
    board_build.flash_mode: dio

      
esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf
#    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

# The captive portal is a fallback mechanism for when connecting to the configured WiFi fails.
# https://esphome.io/components/captive_portal.html
captive_portal:

light:
  - platform: status_led
    name: "Status LED"
    id: esp_status_led
    icon: "mdi:alarm-light"
    pin:
      number: GPIO8
      inverted: true
    restore_mode: ALWAYS_OFF

logger:
  baud_rate: 0

api:

ota:
  - platform: esphome
  
time:
  - platform: homeassistant
    id: homeassistant_time
    
#deep_sleep:
#  run_duration: 40s
#  sleep_duration: 10min
#  id: preserve_battery

switch:
  - platform: gpio
    pin: 
      number: GPIO5
      inverted: false
    restore_mode: ALWAYS_OFF
    id: relay
    name: "${device_name} Relay"
#    on_turn_on:
#     - deep_sleep.prevent: preserve_battery
#    on_turn_off:
#     - deep_sleep.allow: preserve_battery

#  - platform: template
#    name: "Prevent deep sleep"
#    icon: "mdi:sleep-off"
#    restore_mode: RESTORE_DEFAULT_OFF
#    optimistic: true
#    turn_on_action:
#     - deep_sleep.prevent: preserve_battery
#    turn_off_action:
#     - deep_sleep.allow: preserve_battery


sensor:
  - platform: adc
    pin: GPIO3
    name: "Battery voltage"
    attenuation: 11db
    samples: 10 
    filters:
     - multiply: 2.0
  - platform: adc
    pin: GPIO4
    name: "Soil moisture"
    unit_of_measurement: "%"
    attenuation: 11db
    samples: 10
    filters:
      - calibrate_linear:
         - 0.94 -> 0.0
         - 2.49 -> 100.0
      - clamp:
         min_value: 0.0
         max_value: 400
         

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO10
      mode: INPUT_PULLDOWN
    name: "Water level low"
